tools:
  exceptions: https://sentry.io/organizations/shawneerizqa/issues/?project=1836850
  logging: https://app.logdna.com/b1e9dedef0/logs/view
  frontend-ci: ../github/workflows/ionic.yml
  backend-ci: ../github/workflows/nodejs.yml

services:
  production: https://dashboard.heroku.com/apps/klucth-app

docs:
  getting_started: ./README.md
  
commands:
  bootstrap: script/bootstrap
  database: https://console.firebase.google.com/u/0/project/dcsil-klutch/database
  server: cd app/server; npm run start:dev

